server:
  port: 8000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/moneymanager}
    username: root
    password: root

  jpa:
    show-sql: true
    open-in-view: false

api.token: ${TOKEN_SECRET:token-secret}

springdoc:
  api-docs:
    path: /api-docs # Specify the path of the OpenAPI documentation
  swagger-ui:
    path: /swagger-ui.html # Specify the path of the Swagger UI
  enabled: true # Enable or disable Swagger UI